$(function()
{
	$("#clmonth").click(function()
	{
		$("#clmonthdiv").show();
		$("#clweekdiv").hide();
		$("#ctmonthdiv").hide();
		$("#ctweekdiv").hide();
		$("#ctdatediv").hide();
		$("#pnmonthdiv").hide();
		$("#pnweekdiv").hide();
		$("#rlmonthdiv").hide();
		$("#pnyeardiv").hide();
		$("#proyeardiv").hide();
		$("#ptmonthdiv").hide();

		$("#ptweekdiv").hide();   
		$("#rlweekdiv").hide();
		$("#rtmonthdiv").hide();
		$("#rtweekdiv").hide();
		$("#rytdatediv").hide();
		$("#tsasasiasdiv").hide();
		$("#displayed").hide();
		
	});

	$("#clweek").click(function()
	{
		$("#clweekdiv").show();
		$("#clmonthdiv").hide();
		$("#ctmonthdiv").hide();
		$("#ctweekdiv").hide();
		$("#ctdatediv").hide();
		$("#pnmonthdiv").hide();
		$("#pnweekdiv").hide();
		$("#rlmonthdiv").hide();
		$("#pnyeardiv").hide();
		$("#proyeardiv").hide();
		$("#ptmonthdiv").hide();
		$("#ptweekdiv").hide();   
		$("#rlweekdiv").hide();
		$("#rtmonthdiv").hide();
		$("#rtweekdiv").hide();
		$("#rytdatediv").hide();
		$("#tsasasiasdiv").hide();
		$("#displayed").hide();
	});

	$("#ctmonth").click(function()
	{
		$("#ctmonthdiv").show();
		$("#clmonthdiv").hide();
		$("#clweekdiv").hide();
		$("#ctweekdiv").hide();
		$("#ctdatediv").hide();
		$("#pnmonthdiv").hide();
		$("#pnweekdiv").hide();
		$("#rlmonthdiv").hide();
		$("#pnyeardiv").hide();
		$("#proyeardiv").hide();
		$("#ptmonthdiv").hide();
		$("#ptweekdiv").hide();   
		$("#rlweekdiv").hide();
		$("#rtmonthdiv").hide();
		$("#rtweekdiv").hide();
		$("#rytdatediv").hide();
		$("#tsasasiasdiv").hide();
		$("#displayed").hide();
	});
	
	$("#ctweek").click(function()
	{
		$("#ctweekdiv").show();
		$("#clmonthdiv").hide();
		$("#clweekdiv").hide();
		$("#ctmonthdiv").hide();
		$("#ctdatediv").hide();
		$("#pnmonthdiv").hide();
		$("#pnweekdiv").hide();
		$("#rlmonthdiv").hide();
		$("#pnyeardiv").hide();
		$("#proyeardiv").hide();
		$("#ptmonthdiv").hide();
		$("#ptweekdiv").hide();   
		$("#rlweekdiv").hide();
		$("#rtmonthdiv").hide();
		$("#rtweekdiv").hide();
		$("#rytdatediv").hide();
		$("#tsasasiasdiv").hide();
		$("#displayed").hide();
	});
	
	$("#ctdate").click(function()
	{
		$("#ctdatediv").show();
		$("#clmonthdiv").hide();
		$("#clweekdiv").hide();
		$("#ctmonthdiv").hide();
		$("#ctweekdiv").hide();
		$("#pnmonthdiv").hide();
		$("#pnweekdiv").hide();
		$("#rlmonthdiv").hide();
		$("#pnyeardiv").hide();
		$("#proyeardiv").hide();
		$("#ptmonthdiv").hide();
		$("#ptweekdiv").hide();   
		$("#rlweekdiv").hide();
		$("#rtmonthdiv").hide();
		$("#rtweekdiv").hide();
		$("#rytdatediv").hide();
		$("#tsasasiasdiv").hide();
		$("#displayed").hide();
	});

	$("#pnmonth").click(function()
	{
		$("#pnmonthdiv").show();
		$("#clmonthdiv").hide();
		$("#clweekdiv").hide();
		$("#ctmonthdiv").hide();
		$("#ctweekdiv").hide();
		$("#ctdatediv").hide();
		$("#pnweekdiv").hide();
		$("#rlmonthdiv").hide();
		$("#pnyeardiv").hide();
		$("#proyeardiv").hide();
		$("#ptmonthdiv").hide();
		$("#ptweekdiv").hide();   
		$("#rlweekdiv").hide();
		$("#rtmonthdiv").hide();
		$("#rtweekdiv").hide();
		$("#rytdatediv").hide();
		$("#tsasasiasdiv").hide();
		$("#displayed").hide();
	});
	
	$("#pnweek").click(function()
	{
		$("#pnweekdiv").show();
		$("#clmonthdiv").hide();
		$("#clweekdiv").hide();
		$("#ctmonthdiv").hide();
		$("#ctweekdiv").hide();
		$("#ctdatediv").hide();
		$("#pnmonthdiv").hide();
		$("#rlmonthdiv").hide();
		$("#pnyeardiv").hide();
		$("#proyeardiv").hide();
		$("#ptmonthdiv").hide();
		$("#ptweekdiv").hide();   
		$("#rlweekdiv").hide();
		$("#rtmonthdiv").hide();
		$("#rtweekdiv").hide();
		$("#rytdatediv").hide();
		$("#tsasasiasdiv").hide();
		$("#displayed").hide();
	});
	
	$("#pnyear").click(function()
	{
		$("#pnyeardiv").show();
		$("#clmonthdiv").hide();
		$("#clweekdiv").hide();
		$("#ctmonthdiv").hide();
		$("#ctweekdiv").hide();
		$("#ctdatediv").hide();
		$("#pnmonthdiv").hide();
		$("#rlmonthdiv").hide();
		$("#pnweekdiv").hide();
		$("#proyeardiv").hide();
		$("#ptmonthdiv").hide();
		$("#ptweekdiv").hide();   
		$("#rlweekdiv").hide();
		$("#rtmonthdivdiv").hide();
		$("#rtweekdiv").hide();
		$("#rytdatediv").hide();
		$("#tsasasiasdiv").hide();
		$("#displayed").hide();
	});
	
	$("#proyear").click(function()
	{
		$("#proyeardiv").show();
		$("#clmonthdiv").hide();
		$("#clweekdiv").hide();
		$("#ctmonthdiv").hide();
		$("#ctweekdiv").hide();
		$("#ctdatediv").hide();
		$("#pnmonthdiv").hide();
		$("#rlmonthdiv").hide();
		$("#pnweekdiv").hide();
		$("#pnyeardiv").hide();
		$("#ptmonthdiv").hide();
		$("#ptweekdiv").hide();   
		$("#rlweekdiv").hide();
		$("#rtmonthdiv").hide();
		$("#rtweekdiv").hide();
		$("#rytdatediv").hide();
		$("#tsasasiasdiv").hide();
		$("#displayed").hide();
	});
	
	$("#ptmonth").click(function()
	{
		$("#ptmonthdiv").show();
		$("#clmonthdiv").hide();
		$("#clweekdiv").hide();
		$("#ctmonthdiv").hide();
		$("#ctweekdiv").hide();
		$("#ctdatediv").hide();
		$("#pnmonthdiv").hide();
		$("#rlmonthdiv").hide();
		$("#pnweekdiv").hide();
		$("#pnyeardiv").hide();
		$("#proyeardiv").hide();
		$("#ptweekdiv").hide();   
		$("#rlweekdiv").hide();
		$("#rtmonthdiv").hide();
		$("#rtweekdiv").hide();
		$("#rytdatediv").hide();
		$("#tsasasiasdiv").hide();
		$("#displayed").hide();
	});

	$("#ptweek").click(function()
	{
		
		$("#ptweekdiv").show();
		$("#ptmonthdiv").hide();
		$("#clmonthdiv").hide();
		$("#clweekdiv").hide();
		$("#ctmonthdiv").hide();
		$("#ctweekdiv").hide();
		$("#ctdatediv").hide();
		$("#pnmonthdiv").hide();
		$("#rlmonthdiv").hide();
		$("#pnweekdiv").hide();
		$("#pnyeardiv").hide();
		$("#proyeardiv").hide();
		$("#rlweekdiv").hide();
		$("#rtmonthdiv").hide();
		$("#rtweekdiv").hide();
		$("#rytdatediv").hide();
		$("#tsasasiasdiv").hide();
		$("#displayed").hide();
	});

	$("#ptweek").click(function()
	{
		
		$("#ptweekdiv").show();
		$("#ptmonthdiv").hide();
		$("#clmonthdiv").hide();
		$("#clweekdiv").hide();
		$("#ctmonthdiv").hide();
		$("#ctweekdiv").hide();
		$("#ctdatediv").hide();
		$("#pnmonthdiv").hide();
		$("#rlmonthdiv").hide();
		$("#pnweekdiv").hide();
		$("#pnyeardiv").hide();
		$("#proyeardiv").hide();
		$("#rlweekdiv").hide();
		$("#rtmonthdiv").hide();
		$("#rtweekdiv").hide();
		$("#rytdatediv").hide();
		$("#tsasasiasdiv").hide();
		$("#displayed").hide();
	});

	$("#rlweek").click(function()
	{
		
		$("#ptweekdiv").hide();
		$("#ptmonthdiv").hide();
		$("#clmonthdiv").hide();
		$("#clweekdiv").hide();
		$("#ctmonthdiv").hide();
		$("#ctweekdiv").hide();
		$("#ctdatediv").hide();
		$("#pnmonthdiv").hide();
		$("#rlmonthdiv").hide();
		$("#pnweekdiv").hide();
		$("#pnyeardiv").hide();
		$("#proyeardiv").hide();
		$("#rlweekdiv").show();
		$("#rtmonthdiv").hide();
		$("#rtweekdiv").hide();
		$("#rytdatediv").hide();
		$("#tsasasiasdiv").hide();
		$("#displayed").hide();
	});

	$("#rlmonth").click(function()
	{
		$("#rlmonthdiv").show();
		$("#clmonthdiv").hide();
		$("#clweekdiv").hide();
		$("#ctmonthdiv").hide();
		$("#ctweekdiv").hide();
		$("#ctdatediv").hide();
		$("#pnmonthdiv").hide();
		$("#pnweekdiv").hide();
		$("#pnyeardiv").hide();
		$("#proyeardiv").hide();
		$("#ptmonthdiv").hide();
		$("#ptweekdiv").hide();   
		$("#rlweekdiv").hide();
		$("#rtmonthdiv").hide();
		$("#rtweekdiv").hide();
		$("#rytdatediv").hide();
		$("#tsasasiasdiv").hide();
		$("#displayed").hide();
	});


	$("#rtmonth").click(function()
	{
		$("#rlmonthdiv").hide();
		$("#clmonthdiv").hide();
		$("#clweekdiv").hide();
		$("#ctmonthdiv").hide();
		$("#ctweekdiv").hide();
		$("#ctdatediv").hide();
		$("#pnmonthdiv").hide();
		$("#pnweekdiv").hide();
		$("#pnyeardiv").hide();
		$("#proyeardiv").hide();
		$("#ptmonthdiv").hide();
		$("#ptweekdiv").hide();   
		$("#rlweekdiv").hide();
		$("#rtmonthdiv").show();
		$("#rtweekdiv").hide();
		$("#rytdatediv").hide();
		$("#tsasasiasdiv").hide();
		$("#displayed").hide();
	});

	$("#rtmonth").click(function()
	{
		$("#rlmonthdiv").hide();
		$("#clmonthdiv").hide();
		$("#clweekdiv").hide();
		$("#ctmonthdiv").hide();
		$("#ctweekdiv").hide();
		$("#ctdatediv").hide();
		$("#pnmonthdiv").hide();
		$("#pnweekdiv").hide();
		$("#pnyeardiv").hide();
		$("#proyeardiv").hide();
		$("#ptmonthdiv").hide();
		$("#ptweekdiv").hide();   
		$("#rlweekdiv").hide();
		$("#rtmonthdiv").show();
		$("#rtweekdiv").hide();
		$("#rytdatediv").hide();
		$("#tsasasiasdiv").hide();
		$("#displayed").hide();
	});

	$("#rtweek").click(function()
	{
		$("#rlmonthdiv").hide();
		$("#clmonthdiv").hide();
		$("#clweekdiv").hide();
		$("#ctmonthdiv").hide();
		$("#ctweekdiv").hide();
		$("#ctdatediv").hide();
		$("#pnmonthdiv").hide();
		$("#pnweekdiv").hide();
		$("#pnyeardiv").hide();
		$("#proyeardiv").hide();
		$("#ptmonthdiv").hide();
		$("#ptweekdiv").hide();   
		$("#rlweekdiv").hide();
		$("#rtmonthdiv").hide();
		$("#rtweekdiv").show();
		$("#rytdatediv").hide();
		$("#tsasasiasdiv").hide();
		$("#displayed").hide();
	});

	$("#rytdate").click(function()
	{
		$("#rlmonthdiv").hide();
		$("#clmonthdiv").hide();
		$("#clweekdiv").hide();
		$("#ctmonthdiv").hide();
		$("#ctweekdiv").hide();
		$("#ctdatediv").hide();
		$("#pnmonthdiv").hide();
		$("#pnweekdiv").hide();
		$("#pnyeardiv").hide();
		$("#proyeardiv").hide();
		$("#ptmonthdiv").hide();
		$("#ptweekdiv").hide();   
		$("#rlweekdiv").hide();
		$("#rtmonthdiv").hide();
		$("#rtweekdiv").hide();
		$("#rytdatediv").show();
		$("#tsasasiasdiv").hide();
		$("#displayed").hide();
	});

	$("#tsasasias").click(function()
	{
		$("#rlmonthdiv").hide();
		$("#clmonthdiv").hide();
		$("#clweekdiv").hide();
		$("#ctmonthdiv").hide();
		$("#ctweekdiv").hide();
		$("#ctdatediv").hide();
		$("#pnmonthdiv").hide();
		$("#pnweekdiv").hide();
		$("#pnyeardiv").hide();
		$("#proyeardiv").hide();
		$("#ptmonthdiv").hide();
		$("#ptweekdiv").hide();   
		$("#rlweekdiv").hide();
		$("#rtmonthdiv").hide();
		$("#rtweekdiv").hide();
		$("#rytdatediv").hide();
		$("#tsasasiasdiv").show();
		$("#displayed").hide();
	});


	$("#disply").click(function()
	{
		$("#displayed").show();
		$("#rlmonthdiv").hide();
		$("#clmonthdiv").hide();
		$("#clweekdiv").hide();
		$("#ctmonthdiv").hide();
		$("#ctweekdiv").hide();
		$("#ctdatediv").hide();
		$("#pnmonthdiv").hide();
		$("#pnweekdiv").hide();
		$("#pnyeardiv").hide();
		$("#proyeardiv").hide();
		$("#ptmonthdiv").hide();
		$("#ptweekdiv").hide();   
		$("#rlweekdiv").hide();
		$("#rtmonthdiv").hide();
		$("#rtweekdiv").hide();
		$("#rytdatediv").hide();
		$("#tsasasiasdiv").hide();
	});

	


	


	
  $(document).ready(function(){
    $('.datepicker').datepicker();
  });
	

	
});